In [13]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_digits

In [2]:
digits= load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [4]:
df=pd.DataFrame(digits.data, digits.target)
df['target']= digits.target
df

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0,9
0,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0,0
8,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0,8
9,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0,9
8,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0,8

In [9]:
X= df.drop('target', axis= 1)
X

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,9.0,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,4.0,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0
0,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0
8,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0
9,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0
8,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,8.0,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0

In [10]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test= train_test_split(X,df.target, test_size=0.2)

USING FOR LOOP FOR HYPERPARAMETERS TUNNING

In [7]:
# from sklearn import svm
# kernels= ['rbf', 'Linear']
# alpha= [1,10,20]
# #models= [SVC]#LogisticRegression(),RandomForestClassifier(), MultinomialNB(),BernoulliNB(), GaussianNB()]
# avg_score= {}
# for kval in kernels:
#     for c in alpha:
#         cv_score= cross_val_score(svm.SVC(kernel=kval,C= c,gamma='auto'),X,df.target, cv=5)
#         avg_score[kval + '_'+str(c)]= np.average(cv_score)
# avg_score

In [11]:
models= {
    'linear': (LogisticRegression(alpha=10)),
    'Mnb': (MultinomialNB(),
    'Bnb': BernoulliNB(),
    'Gaus': GaussianNB(),
    'Rfst': RandomForestClassifier()
    'Svm': SVC('auto'),kernel='rbf',C=30,gamma='auto'
}

SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' on line 3 (2582870226.py, line 8)

In [15]:
from sklearn.model_selection import GridSearchCV

clf= GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,20,10],
    'kernel': ['linear', 'rbf']
}, cv=5, return_train_score=False)
clf.fit(X_train, y_train)
clf.cv_results_

{'mean_fit_time': array([0.06135592, 0.44428616, 0.06080008, 0.4707953 , 0.08621411,
        0.52494168]),
 'std_fit_time': array([0.00362204, 0.00537716, 0.00223537, 0.03223289, 0.0055336 ,
        0.06388319]),
 'mean_score_time': array([0.01634822, 0.12669835, 0.01729503, 0.13503976, 0.02630997,
        0.16636691]),
 'std_score_time': array([0.00107341, 0.00632315, 0.00533144, 0.01153189, 0.0008579 ,
        0.03570626]),
 'param_C': masked_array(data=[1, 1, 20, 20, 10, 10],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'}],
 'split0_test_score': array([0.97569444, 0.35763889, 0.97569444, 0.40277778, 0.97569444,
        0.40277778]),
 'split1_test_score': array([0.98263889, 0.42013889, 0.98263889, 0.47222222, 0.98263889,
        0.47222222]),
 'split2_test_score': array([0.96864111, 0.40069686, 0.96864111, 0.45644599, 0.96864111,
        0.45644599]),
 'split3_test_score': array([0.96864111, 0.44599303, 0.96864111, 0.47735192, 0.96864111,
        0.47735192]),
 'split4_test_score': array([0.97560976, 0.44599303, 0.97560976, 0.4912892 , 0.97560976,
        0.4912892 ]),
 'mean_test_score': array([0.97424506, 0.41409214, 0.97424506, 0.46001742, 0.97424506,
        0.46001742]),
 'std_test_score': array([0.00523885, 0.03297969, 0.00523885, 0.03071318, 0.00523885,
        0.03071318]),
 'rank_test_score': array([1, 6, 1, 4, 1, 4])}

The printed Information from The above cell can be put into a Dataframe for easy comprehension

In [17]:
table= pd.DataFrame(clf.cv_results_)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.061356,0.003622,0.016348,0.001073,1,linear,"{'C': 1, 'kernel': 'linear'}",0.975694,0.982639,0.968641,0.968641,0.975610,0.974245,0.005239,1
1,0.444286,0.005377,0.126698,0.006323,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.357639,0.420139,0.400697,0.445993,0.445993,0.414092,0.032980,6
2,0.060800,0.002235,0.017295,0.005331,20,linear,"{'C': 20, 'kernel': 'linear'}",0.975694,0.982639,0.968641,0.968641,0.975610,0.974245,0.005239,1
3,0.470795,0.032233,0.135040,0.011532,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.402778,0.472222,0.456446,0.477352,0.491289,0.460017,0.030713,4
4,0.086214,0.005534,0.026310,0.000858,10,linear,"{'C': 10, 'kernel': 'linear'}",0.975694,0.982639,0.968641,0.968641,0.975610,0.974245,0.005239,1
5,0.524942,0.063883,0.166367,0.035706,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.402778,0.472222,0.456446,0.477352,0.491289,0.460017,0.030713,4

In [18]:
df=table[['param_C','param_kernel','params','mean_test_score']]
df

  param_C param_kernel                         params  mean_test_score
0       1       linear   {'C': 1, 'kernel': 'linear'}         0.974245
1       1          rbf      {'C': 1, 'kernel': 'rbf'}         0.414092
2      20       linear  {'C': 20, 'kernel': 'linear'}         0.974245
3      20          rbf     {'C': 20, 'kernel': 'rbf'}         0.460017
4      10       linear  {'C': 10, 'kernel': 'linear'}         0.974245
5      10          rbf     {'C': 10, 'kernel': 'rbf'}         0.460017

letd check for classes in our table dataframe

In [19]:
dir(table)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'mean_fit_time',
 'mean_score_time',
 'mean_test_score',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'param_C',
 'param_kernel',
 'params',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rank_test_score',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'split0_test_score',
 'split1_test_score',
 'split2_test_score',
 'split3_test_score',
 'split4_test_score',
 'squeeze',
 'stack',
 'std',
 'std_fit_time',
 'std_score_time',
 'std_test_score',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [20]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [22]:
clf.best_score_

0.9742450638792104

In other to reduce the number of Iteration so as to save Computational Cost, Developers make use of RANDOMSEARCH  Method, which 
take few random parameters and use it to select the best Hyperparameters.

In [43]:
from sklearn.model_selection import RandomizedSearchCV
rms= RandomizedSearchCV(svm.SVC(gamma= 'auto'), {
    'kernel': ('linear', 'rbf'),
    'C':(1,10,20,30)}, cv=5, return_train_score= False, n_iter=3)
rms.fit(X_train,y_train)
rms.cv_results_

{'mean_fit_time': array([0.52021689, 0.06696529, 0.46288238]),
 'std_fit_time': array([0.04501471, 0.01123331, 0.04708054]),
 'mean_score_time': array([0.17042742, 0.01729274, 0.12500753]),
 'std_score_time': array([0.05257834, 0.001586  , 0.00810427]),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf'],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'param_C': masked_array(data=[1, 20, 30],
              mask=[False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'kernel': 'rbf', 'C': 1},
  {'kernel': 'linear', 'C': 20},
  {'kernel': 'rbf', 'C': 30}],
 'split0_test_score': array([0.35763889, 0.97569444, 0.40277778]),
 'split1_test_score': array([0.42013889, 0.98263889, 0.47222222]),
 'split2_test_score': array([0.40069686, 0.96864111, 0.45644599]),
 'split3_test_score': array([0.44599303, 0.96864111, 0.47735192]),
 'split4_test_score': array([0.44599303, 0.97560976, 0.4912892 ]),
 'mean_test_score': array([0.41409214, 0.97424506, 0.46001742]),
 'std_test_score': array([0.03297969, 0.00523885, 0.03071318]),
 'rank_test_score': array([3, 1, 2])}

In [44]:
df2= pd.DataFrame(rms.cv_results_)
df2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.520217,0.045015,0.170427,0.052578,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.357639,0.420139,0.400697,0.445993,0.445993,0.414092,0.032980,3
1,0.066965,0.011233,0.017293,0.001586,linear,20,"{'kernel': 'linear', 'C': 20}",0.975694,0.982639,0.968641,0.968641,0.975610,0.974245,0.005239,1
2,0.462882,0.047081,0.125008,0.008104,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.402778,0.472222,0.456446,0.477352,0.491289,0.460017,0.030713,2

In [42]:
df2[['param_kernel','param_C','params','mean_test_score']]

  param_kernel param_C                         params  mean_test_score
0       linear      10  {'kernel': 'linear', 'C': 10}         0.974245
1       linear      20  {'kernel': 'linear', 'C': 20}         0.974245

For testing with several model with diferent parameters, we can make use of the following simple method

In [53]:
model_chars= {
    'SVC': {
        'model' :SVC(),
        'param': {
            'kernel': ['rbf','linear'],
        'C': [1,10,20]}
           },
    'LogisticRegression': {
        'model' :LogisticRegression(solver='liblinear',multi_class='auto'),
        'param': {
        'C': [1,10,20]},
           },
    'RandomForest': {
        'model' :RandomForestClassifier(),
        'param': {
          
        'n_estimators': [40,30,20]}
    },
    'MultinomialNB': {
        
        'model' :MultinomialNB(),
    },
    "DecisionTree":{
        'model' :DecisionTree(),
        'param': {
            'Gini': [10,20,9]
            'S': [30,20,10]
        }
    }

SyntaxError: invalid syntax (396556376.py, line 1)